name: infra-project-genai-DEBUG

on:
    #push:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Github Environment to get variables and secrets from [dev,stage,prod]'
          required: true
          default: 'dev'
env:
    # Flow control
    ENABLE_STEP: 'true' # Enable/Disable a step
    
    # ADMIN usual culprits - verify, twice. (only configure once)
    admin_bicep_kv_fw: "esaifac-seeding-sdc-001" # seeding keyvault, name
    admin_bicep_kv_fw_rg: "spoke-aifactory-sdc-dev-001" #seeding keyvault, resource group
    admin_aifactorySuffixRG: "-002"
    common-sp-appid-seeding-kv-name: "esml-common-bicep-sp-id"
    common-sp-secret-seeding-kv-name: "esml-common-bicep-sp-secret"
    admin_hybridBenefit: false # Enable Hybrid Benefits if provisioning VM access via Bastion
    admin_commonResourceSuffix: "-001"
    admin_prjResourceSuffix: "-001"

    # ADMIN specific START (only configure once)
    admin_ip_fw: "192.x.x.x" # Do not touch. leave as-is. This is just a placeholder a script will populate later.
    admin_bicep_input_keyvault_subscription: "${{ secrets.AIFACTORY_SEEDING_KEYVAULT_SUBSCRIPTION_ID }}" # seeding keyvault, subscription id
    #admin_location: "${{ vars.AIFACTORY_LOCATION }}"
    #admin_locationSuffix: "${{ vars.AIFACTORY_LOCATION_SHORT }}"
    dev_test_prod_sub_id: "${{ vars.AZURE_SUBSCRIPTION_ID }}" # "a1234567-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    #dev_test_prod: "${{ vars.AZURE_ENV_NAME }}" # ESML AIFactory environment: [dev,test,prod]
   
    # PROJECT specific START (configure for each project)
    project_IP_whitelist: "${{ secrets.PROJECT_MEMBERS_IP_ADDRESS }}" # "192.x.x.x"
    technical_admins_ad_object_id: "${{ secrets.PROJECT_MEMBERS }}"  # comma separated list with no spaces: "012345ab-xxxx-xxxx-xxxx-xxxxxxxxxxxx,1234f-af-234-adfssdf,12312-aef23431"
    technical_admins_email: "${{ vars.PROJECT_MEMBERS_EMAILS }}"  # comma separated list
    project_number_000: "007" # Project number (3 digits)
    project_service_principal_AppID_seeding_kv_name: "esml-project001-sp-id" # Service principle ID, name from seeding keyvault (need to be from enterprise application)
    project_service_principal_OID_seeding_kv_name: "esml-project001-sp-oid" # Service principle Object ID, name from seeding keyvault (need to be from enterprise application)
    project_service_principal_Secret_seeding_kv_name: "esml-project001-sp-secret" # Service principle secret, name from seeding keyvault
    
    # PROJECT TYPE specific
    admin_projectType: "genai-1" # Project type, [esml,genai-1]
    useCommonACR: true # Use common Azure Container Registry (save cost), insted of each project having its own.

    # OPTIONAL - GENAI specific
    admin_enablePublicGenAIAccess: true # Enable public access to GenAI
    optional_serviceSettingDeployAIDocIntelligence: false # Deploy AI Doc Intelligence
    optional_serviceSettingDeployAzureAIVision: false # Deploy Azure AI Vision
    optional_serviceSettingDeployAzureSpeech: false # Deploy Azure Speech
    optional_serviceSettingDeployAzureAppService: false # Deploy Azure App Service and a WebApp
    optional_serviceSettingDeployAzureFunction: false # Deploy Azure App Service and a WebApp
    optional_serviceSettingDeployAzureContainerApps: false # Deploy Azure ContainerApps
    optional_serviceSettingDeployAzureCosmosDB: false # Deploy Azure CosmosDB
    # OPTIONAL - ESML specific
    admin_aks_gpu_sku_dev_override: "Standard_B4ms" # AKS GPU SKU for dev
    admin_aks_gpu_sku_test_prod_override: Standard_DS13-2_v2 # AKS GPU SKU for test/prod
    admin_aks_nodes_dev_override: 1 # AKS nodes for dev
    admin_aks_nodes_testProd_override: 3 # AKS nodes for test/prod
    admin_aks_version_override: "1.30.3" # AKS version
    admin_aml_cluster_maxNodes_dev_override: 3 # AML cluster max nodes for dev
    admin_aml_cluster_maxNodes_testProd_override: 5 # AML cluster max nodes for test/prod
    admin_aml_cluster_sku_dev_override: "Standard_DS3_v2" # AML cluster SKU for dev
    admin_aml_cluster_sku_testProd_override: "Standard_D13_v2" # AML cluster SKU for test/prod
    admin_aml_computeInstance_dev_sku_override: "Standard_DS11_v2" # AML compute instance SKU for dev
    admin_aml_computeInstance_testProd_sku_override: "Standard_ND96amsr_A100_v4" # AML compute instance SKU for test/prod
    admin_private_azureMLStudioUI: true # Private Azure ML Studio UI
    admin_private_DatabricksUI: false # Private Databricks UI
jobs:
  debug-powershell:
    name: Debug powershell
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: List RUNNER directory
      run: ls -al ${{ runner.workspace }}
    - name: List RUNNER /aifactory/debug/
      run: ls -al ${{ runner.workspace }}/aifactory/debug/"
    - name: Set permissions
      run: chmod -R 755 ${{ github.workspace }}
    - name: List workspace directory
      run: ls -al ${{ github.workspace }}
    - name: List aifactory directory
      run: ls -al ${{ github.workspace }}/../
    - name: Check directory
      run: ls -al "/home/runner/work/azure-enterprise-scale-ml-usage-2/aifactory/debug/"

    - name: Set permissions
      run: chmod -R 755 "/home/runner/work/azure-enterprise-scale-ml-usage-2/aifactory/debug/"

    - name: Check PowerShell version
      run: pwsh -v

    - name: 20_DEBUG_CalcSubnet
      working-directory: "/home/runner/work/azure-enterprise-scale-ml-usage-2/aifactory/debug/"
      run: |
        sudo pwsh -Command /home/runner/work/azure-enterprise-scale-ml-usage-2/aifactory/debug/subnetCalc.ps1 -bicepPar1 './aifactory/parameters/10-esml-globals-1.json' -bicepPar2 './aifactory/parameters/10-esml-globals-2-12_13_21_22.json' -bicepPar3 './aifactory/parameters/10-esml-globals-4-13_21_22.json' -bicepPar4 './aifactory/parameters/21-22-esml-prj-parameters.json' -bicepPar5 './aifactory/parameters/10-esml-globals-override.json' -filePath './aifactory/parameters/' -spObjId '${{ env.common-sp-appid-value }}' -spSecret '${{ env.common-sp-secret-value }}' -env '${{ env.dev_test_prod }}' -subscriptionId '${{ env.test_sub_id }}' -prjResourceSuffix '${{ env.admin_prjResourceSuffix }}' -aifactorySuffixRGADO '${{ env.admin_aifactorySuffixRG }}' -commonResourceSuffixADO '${{ env.admin_commonResourceSuffix }}' -locationADO '${{ vars.AIFACTORY_LOCATION}}' -locationSuffixADO '${{ vars.AIFACTORY_LOCATION_SHORT }}' -projectTypeADO '${{ env.admin_projectType }} -useServicePrincipal"
      shell: pwsh
